import sqlite3

conn = sqlite3.connect('mdb.db')
# cur = conn.cursor()
# conn.execute("DROP TABLE IF EXISTS employees")
# conn.execute("DROP TABLE IF EXISTS admin")
# conn.execute("DROP TABLE IF EXISTS vendinghistory")
# conn.execute("DROP TABLE IF EXISTS session")
# conn.execute("DROP TABLE IF EXISTS mdbevent")
# conn.execute("DROP TABLE IF EXISTS dayoff")
# conn.execute("DROP TABLE IF EXISTS dayoffweek")
# conn.execute('CREATE TABLE employees ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, empID TEXT, cardID TEXT UNIQUE, itemLimit INT, leftItem INT, status INT, loginTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP)')
# conn.execute('CREATE TABLE admin (name TEXT, email TEXT, password TEXT, itemLimit INT)')
# conn.execute('CREATE TABLE vendinghistory ( id INTEGER PRIMARY KEY AUTOINCREMENT, cardID TEXT, itemType INT, amount INT, status INT, logDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP)')
# conn.execute('CREATE TABLE session (currentCard TEXT, vendStatus INT)')
# conn.execute('INSERT INTO session (currentCard, vendStatus) VALUES (?,?)',("", 0))
# conn.commit()
# conn.execute('CREATE TABLE mdbevent (dailylimit INT, machineStatus INT)')
# conn.execute('INSERT INTO mdbevent (dailylimit, machineStatus) VALUES (?,?)',(5,1))
# conn.commit()
# conn.execute('CREATE TABLE dayoff (date TIMESTAMP, machineStatus INT )')
# conn.execute('CREATE TABLE dayoffweek (day INT, machineStatus INT )')
# conn.execute('INSERT INTO dayoffweek (day, machineStatus) VALUES (?,?)',(1, 1))
# conn.execute('INSERT INTO dayoffweek (day, machineStatus) VALUES (?,?)',(2, 1))
# conn.execute('INSERT INTO dayoffweek (day, machineStatus) VALUES (?,?)',(3, 1))
# conn.execute('INSERT INTO dayoffweek (day, machineStatus) VALUES (?,?)',(4, 1))
# conn.execute('INSERT INTO dayoffweek (day, machineStatus) VALUES (?,?)',(5, 1))
# conn.execute('INSERT INTO dayoffweek (day, machineStatus) VALUES (?,?)',(6, 1))
# conn.execute('INSERT INTO dayoffweek (day, machineStatus) VALUES (?,?)',(7, 1))
conn.execute('CREATE TABLE machinetimer (startHour TIMESTAMP,startMinute TIMESTAMP,endHour TIMESTAMP,endMinute TIMESTAMP)')
conn.execute('INSERT INTO machinetimer (startHour,startMinute,endHour,endMinute) VALUES (?,?,?,?)',("09", "00", "18","30",))
conn.commit()
conn.close()
# employeestatus 1-active, 2-pending, 0-denied
# machinestatus 0-off, 1-on
# vendstatus 0-off, 1-on